export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  PLAN_NOT_APPROVED: "PLAN_NOT_APPROVED",
  OPEN_OBSERVATION_EXISTS: "OPEN_OBSERVATION_EXISTS",
  OBSERVATION_NOT_FOUND: "OBSERVATION_NOT_FOUND",
  OBSERVATION_STATUS_ILLEGAL: "OBSERVATION_STATUS_ILLEGAL",
  ENTRY_SLOT_DUPLICATED: "ENTRY_SLOT_DUPLICATED",
  ENTRY_IMAGE_REQUIRED: "ENTRY_IMAGE_REQUIRED",
  REVIEW_SELF_FORBIDDEN: "REVIEW_SELF_FORBIDDEN",
  REVIEW_BLOCKED: "REVIEW_BLOCKED",
  PLAN_ARCHIVE_BLOCKED: "PLAN_ARCHIVE_BLOCKED",
  SOURCE_NOT_FOUND: "SOURCE_NOT_FOUND"
} as const;
