export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  OBSERVATION_LIMIT: "OBSERVATION_LIMIT",
  OBSERVATION_NOT_FOUND: "OBSERVATION_NOT_FOUND",
  OBSERVATION_NOT_PENDING: "OBSERVATION_NOT_PENDING",
  OBSERVATION_REVIEW_SELF: "OBSERVATION_REVIEW_SELF",
  OBSERVATION_BLOCKERS_PRESENT: "OBSERVATION_BLOCKERS_PRESENT",
  PLAN_NOT_APPROVED: "PLAN_NOT_APPROVED",
  ARCHIVE_GATE_DENIED: "ARCHIVE_GATE_DENIED",
  SOURCE_NOT_FOUND: "SOURCE_NOT_FOUND"
} as const;
