export const createStabilityObservationDto = (overrides = {}) => ({
  id: 1,
  plan_id: 1,
  relic_id: 1,
  position_desc: "口沿补配处",
  period_start: "2026-06-20T09:00:00Z",
  period_end: "2026-06-27T18:00:00Z",
  temp_min_limit: 18,
  temp_max_limit: 22,
  humidity_min_limit: 50,
  humidity_max_limit: 60,
  observation_status: "UNDER_OBSERVATION",
  blocker_reasons: [],
  created_by: 1,
  created_at: "2026-06-20T09:00:00Z",
  finished_by: null,
  finished_at: null,
  reviewed_by: null,
  reviewed_at: null,
  review_comment: null,
  last_result: null,
  last_calculated_at: null,
  checkpoints: [],
  revisions: [],
  ...overrides
});
